Biblioteca.Web/Controllers/BooksController.cs
using Biblioteca.Web.Data;
using Biblioteca.Web.Helpers;
using Biblioteca.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Biblioteca.Web.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IGenreRepository _genreRepository;
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILendRepository _lendRepository;

        public BooksController(IBookRepository bookRepository, IUserHelper userHelper,
            IConverterHelper converterHelper,
             IBlobHelper blobHelper, IGenreRepository genreRepository,
             DataContext context, IWebHostEnvironment webHostEnvironment,
             ILendRepository lendRepository)
        {
            _bookRepository = bookRepository;
            _userHelper = userHelper;
            _converterHelper = converterHelper;
            _blobHelper = blobHelper;
            _genreRepository = genreRepository;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _lendRepository = lendRepository;
        }

        // GET: Books
        public IActionResult Index(string search)
        {
            return View(_context.Books.Where(x => x.Title.Contains(search) || x.Author.Contains(search) || x.GenreName.Contains(search)
            || x.ISBN.Contains(search) || x.Publisher.Contains(search) || search == null).ToList());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var book = await _bookRepository.GetByIdAsync(id.Value);
            if (book == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            return View(book);
        }

        // GET: Books/Create
        [RoleAuthorization("Admin", "Staff", "Reader")]
        public IActionResult Create()
        {
            var genres = _genreRepository.GetAll().ToList();
            ViewBag.Genres = new SelectList(genres, "Name", "Name");

            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [RoleAuthorization("Admin", "Staff", "Reader")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.BookPdf != null)
                {
                    string folder = "books";
                    string pdfUrl = await UploadFile(folder, model.BookPdf); // Get the URL of the uploaded PDF

                    Guid coverId = Guid.Empty;

                    if (model.ImageFile != null && model.ImageFile.Length > 0)
                    {
                        coverId = await _blobHelper.UploadBlobAsync(model.ImageFile, "covers");
                    }

                    var book = _converterHelper.ToBook(model, coverId, true);

                    var existingBookWithSameBookId = await _bookRepository.GetBookByBookIdAsync(model.Id);
                    if (existingBookWithSameBookId != null && existingBookWithSameBookId.Id != model.Id)
                    {
                        ModelState.AddModelError("BookId", "A book with the same ISBN already exists.");
                        // Repopulate the genre dropdown if needed
                        var genres = _genreRepository.GetAll().ToList();
                        ViewBag.Genres = new SelectList(genres, "Name", "Name");
                        return View(model);
                    }

                    // Genre name based on the user's selection
                    book.GenreName = model.GenreName;

                    // Set the PDF URL property of the book
                    book.BookPdfUrl = pdfUrl;

                    book.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    await _bookRepository.CreateAsync(book);

                    return RedirectToAction(nameof(Index));
                }

                return View(model);
            }

            return View(model);
        }


        private async Task<string> UploadFile(string folderPath, IFormFile file)
        {
            folderPath = "books/" + Guid.NewGuid().ToString() + "_" + file.FileName; // Change this line

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }



        // GET: Books/Edit/5
        [RoleAuthorization("Staff", "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var book = await _bookRepository.GetByIdAsync(id.Value);
            if (book == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var model = _converterHelper.ToBookViewModel(book);

            // Retrieve the book's genre and set it in the model
            var bookGenre = await _genreRepository.GetGenreByNameAsync(book.GenreName);
            if (bookGenre != null)
            {
                model.GenreName = bookGenre.Name;
            }

            // Ensure that the "IsAvailable" property in the model matches the book's availability status
            model.IsAvailable = book.IsAvailable;

            // Retrieve the list of genres and update ViewBag.Genres
            var genres = _genreRepository.GetAll().ToList();
            ViewBag.Genres = new SelectList(genres, "Name", "Name");

            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [RoleAuthorization("Staff", "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookViewModel model)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    Guid coverId = model.CoverId;

                    if (model.ImageFile != null && model.ImageFile.Length > 0)
                    {
                        coverId = await _blobHelper.UploadBlobAsync(model.ImageFile, "covers");
                    }

                    var book = await _bookRepository.GetBookByIdAsync(model.Id);

                    if (book == null)
                    {
                        return NotFound(); // Handle the case where the book is not found
                    }

                    //if (_context.Books.Any(a => a.BookId.Equals(model.BookId)))
                    //{
                    //    ModelState.AddModelError("BookId ", "Book already exists!!");
                    //}

                    // Check for duplicate ISBN
                    var existingBookWithSameBookId = await _bookRepository.GetBookByBookIdAsync(model.Id);
                    if (existingBookWithSameBookId != null && existingBookWithSameBookId.Id != model.Id)
                    {
                        ModelState.AddModelError("Id", "A book with the same Id already exists.");
                        // Repopulate the genre dropdown if needed
                        var genres = _genreRepository.GetAll().ToList();
                        ViewBag.Genres = new SelectList(genres, "Name", "Name");
                        return View(model);
                    }

                    // Check if a new PDF is provided for the book update
                    if (model.BookPdf != null)
                    {
                        string folder = "books";
                        string pdfUrl = await UploadFile(folder, model.BookPdf); // Get the URL of the uploaded PDF
                        book.BookPdfUrl = pdfUrl;
                    }

                    // Update genre name based on the user's selection
                    book.GenreName = model.GenreName;
                    book.CoverId = coverId;
                    book.Author = model.Author;
                    book.Title = model.Title;
                    book.Borrower = model.Borrower;
                    book.ISBN = model.ISBN;
                    book.Publisher = model.Publisher;
                    book.AvailableCopies = model.AvailableCopies;

                    
                    // Update the availability status based on the checkbox value
                    //book.IsAvailable = model.IsAvailable;

                    book.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);

                    await _bookRepository.UpdateAsync(book);
                }
                catch (DbUpdateConcurrencyException)
                {
                    // Check for concurrency exception based on the book's BookId
                    if (!await _bookRepository.ExistAsync(model.Id))
                    {
                        return NotFound();
                    }
                    else

Biblioteca.Web/Controllers/CitiesController.cs
using Biblioteca.Web.Data;
using Biblioteca.Web.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System;
using Biblioteca.Web.Models;
using Microsoft.WindowsAzure.Storage;

namespace Biblioteca.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly ICityRepository _cityRepository;

        public CitiesController(
            ICityRepository cityRepository)
        {
            _cityRepository = cityRepository;
        }

        public async Task<IActionResult> DeleteLibrary(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var library = await _cityRepository.GetLibraryAsync(id.Value);
            if (library == null)
            {
                return NotFound();
            }

            var cityId = await _cityRepository.DeleteLibraryAsync(library);
            return this.RedirectToAction($"Details", new { id = cityId });
        }

        public async Task<IActionResult> EditLibrary(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var library = await _cityRepository.GetLibraryAsync(id.Value);
            if (library == null)
            {
                return NotFound();
            }

            return View(library);
        }

        [HttpPost]
        public async Task<IActionResult> EditLibrary(Library library)
        {
            if (this.ModelState.IsValid)
            {
                var cityId = await _cityRepository.UpdateLibraryAsync(library);
                if (cityId != 0)
                {
                    return this.RedirectToAction($"Details", new { id = cityId });
                }
            }

            return this.View(library);
        }

        public async Task<IActionResult> AddLibrary(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _cityRepository.GetByIdAsync(id.Value);
            if (city == null)
            {
                return NotFound();
            }

            var model = new LibraryViewModel { CityId = city.Id };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddLibrary(LibraryViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await _cityRepository.AddLibraryAsync(model);
                return RedirectToAction("Details", new { id = model.CityId });
            }

            return View(model);
        }

        public IActionResult Index()
        {
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"];
            }

            return View(_cityRepository.GetCitiesWithLibraries());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _cityRepository.GetCityWithLibrariesAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(City city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _cityRepository.CreateAsync(city);
                    TempData["SuccessMessage"] = "City created successfully!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = "This city already exists!.";
                    //_flashMessage.Danger("This city already exists!");
                }

                return View(city);
            }

            return View(city);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _cityRepository.GetByIdAsync(id.Value);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(City city)
        {
            if (ModelState.IsValid)
            {
                await _cityRepository.UpdateAsync(city);
                return RedirectToAction(nameof(Index));
            }

            return View(city);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var city = await _cityRepository.GetCityWithLibrariesAsync(id.Value);
            if (city.Libraries.Count > 0) // To avoid cascade delete
            {
                //this.ViewBag.ErrorTitle = "Error";
                //this.ViewBag.ErrorMessage = "In order to delete this city, you must first delete the libraries within it.";
                return RedirectToAction("CascadeError", "Errors");
            }

            await _cityRepository.DeleteAsync(city);
            return RedirectToAction(nameof(Index));
        }
    }
}

Biblioteca.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
    @* <link rel="stylesheet" href="~/css/site.css" /> *@
    <link rel="stylesheet" href="~/css/site2.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="icon" href="~/images/horizontal_pattern_icon.ico" type="image/x-icon">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Books </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Books" asp-action="Index">Books</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a></li>
                                 
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Newsletters" asp-action="Index">News</a>
                        </li>
                        @if(this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Create">Create User</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="UserList">User List</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Cities" asp-action="Index">Cities and Libraries</a></li>
                                </ul>
                            </li>
                        }
                    </ul>

                    <ul class="nav navbar-nav navbar-righ text-dark">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Lends</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Lends" asp-action="Index">Lends</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Lends" asp-action="History">History</a></li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-area="" asp-controller="Contacts" asp-action="Contact">Contact Us!</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>